<?php


use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;

$user= Data::get("user");?>
<div class="modal-header">
    <h5 class="modal-title" id="InfoUserLabel">Banir utilizador</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <p>Tem a certeza que quere banir o utilizar <b><?=$user->username?></b> ?</p>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
    <a href="<?=URL::toRoute("user/ban",$user->iduser)?>">
        <button type="button" class="btn btn-danger">Confirmar</button>
    </a>
</div>