<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;

$user= Data::get("user");
?>
<div class="modal-header">
    <h5 class="modal-title" id="InfoUserLabel"><?=$user->username?></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <table class="table">
        <tbody>
            <tr>
                <th>Nome:</th>
                <td><?=$user->name?></td>
            </tr>
            <tr>
                <th>Email:</th>
                <td><?=$user->email?></td>
            </tr>
        </tbody>
    </table>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Ok</button>
</div>
