<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author"      content="Yaroslav Antonenko">

    <title>Shut the box</title>

    <?=AssetBundler::css()?>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png')?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css')?>" media="screen" >
    <link rel="stylesheet" href="<?= Asset::css('/game.css')?>" media="screen" >


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js')?>"></script>
    <script src="<?= Asset::js('respond.min.js')?>"></script>
    <![endif]-->
</head>
<style>
    body{
        background-image: url("<?=Asset::image('bg.jpg')?>");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
</style>
<body class="home">
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom" >
    <div class="container">
        <div class="navbar-header">
            <!-- Button for smallest screens -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand" href="<?= URL::toRoute('home/index')?>"><img src="<?= Asset::image('logo.png')?>" alt="Shut the box"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                <li><a href="<?= URL::toRoute('home/top')?>">Top 10</a></li>
                <?php
                if(Session::has("userid"))
                {
                    ?>
                    <li><a href="<?= URL::toRoute('user/profile',Session::get("userid"))?>">Welcome <?=User::find(Session::get("userid"))->username?></a></li>
                    <li><a class="btn" href="<?= URL::toRoute('user/logout')?>">LOGOUT </a></li>
                    <?php  if(Session::get("role")=="ADMIN" && strpos($_SERVER["REQUEST_URI"],"backoffice") === false) { ?>
                    <li><a class="btn" href="<?= URL::toRoute('backoffice/allusers')?>">Backoffice</a></li>
                    <?php
                    }
                }
                else
                {
                    ?>
                    <li><a class="btn" href="<?= URL::toRoute('user/login')?>">SIGN IN </a></li>
                    <li><a class="btn" href="<?= URL::toRoute('user/register')?>">SIGN UP</a></li>
                <?php
                }
                ?>

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
<!-- /.navbar -->
<header id="head" class="secondary"></header>