<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>
<style>
    body{
        background-image: url("<?=Asset::image('bg.jpg')?>");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
    footer {
        position: absolute;
        bottom: 0;
        width: 100%; /* Footer height */
    }


    button {
        position: absolute;
        top: 50%;
    }
</style>

    <div class="container">
        <div class="row">
            <h1>Bem vindo ao jogo</h1>
            <button class="btn btn-danger">Iniciar jogo</button>

        </div>
    </div>

<?php Layout::includeLayout('footer')?>