<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
Layout::includeLayout('sidebar');


$users = Data::get("users");
?>

<style>
    i {
        cursor: pointer;
    }
    .fa-eye {
        color: #39afff;
    }
    .fa-ban{
        color: #ff5853;
    }
    .fa-check-circle-o{
        color: #8bff6d;
    }
</style>
    <div class="content">
        <div class="container">

                <div class="row" style="margin-top:20px ">
                    <div class="col-xs-6">
                        <input id="search_user" onkeyup="searchuser('<?=URL::toRoute("ajax/finduser")?>')" type="text" class="form-control" placeholder="Procurar....">
                    </div>
                </div>


        <table id="allusers" class="table" >
            <thead>
                <tr>
                    <th colspan="100%">Users</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($users as $user){
                    ?>
                    <tr>
                        <td><?=$user->username?></td>
                        <td><?=$user->email?></td>
                        <td><?=$user->name?></td>
                        <td>
                            <i class="fa fa-eye fa-2x" data-toggle="modal" data-target="#infoUser" onclick="showUserInformation('<?=URL::toRoute("ajax/infouser")?>',<?=$user->iduser?>)"></i>
                            <?php if($user->activeted==1) { ?>
                                <i class="fa fa-ban fa-2x" data-toggle="modal" data-target="#banedUsermodal" onclick="bannedUser('<?=URL::toRoute("ajax/banuser")?>',<?=$user->iduser?>)"></i>
                            <?php  } else { ?>
                                <i class="fa fa-check-circle-o fa-2x" data-toggle="modal" data-target="#banedUsermodal" onclick="unbannedUser('<?=URL::toRoute("ajax/unbanuser")?>',<?=$user->iduser?>)"></i>
                            <?php } ?>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
        </div>

</div>

<script src="<?= Asset::js('users.js')?>"></script>
<?php Layout::includeLayout("footerBackend");
?>
<div class="modal fade" id="infoUser" tabindex="-1" role="dialog" aria-labelledby="InfoUserLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>
<div class="modal fade" id="banedUsermodal" tabindex="-1" role="dialog" aria-labelledby="banedUsermodal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>
