<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
Layout::includeLayout('sidebar'); ?>
<style>
    i {
        cursor: pointer;
    }
    .fa-eye {
        color: #39afff;
    }
    .fa-trash-o{
        color: #ff5853;
    }
</style>
    <div class="content">
        <div class="container">


        <table id="allusers" class="table" style="margin-top:20px ">
            <thead>
                <tr>
                    <th colspan="100%">Users</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Username</td>
                    <td>Email</td>
                    <td>Name</td>
                    <td><i class="fa fa-eye"></i> <i class="fa fa-trash-o"></i></td>
                </tr>
                <tr>
                    <td>Username</td>
                    <td>Email</td>
                    <td>Name</td>
                    <td><i class="fa fa-eye"></i> <i class="fa fa-trash-o"></i></td>
                </tr>
                <tr>
                    <td>Username</td>
                    <td>Email</td>
                    <td>Name</td>
                    <td><i class="fa fa-eye"></i> <i class="fa fa-trash-o"></i></td>
                </tr>
                <tr>
                    <td>Username</td>
                    <td>Email</td>
                    <td>Name</td>
                    <td><i class="fa fa-eye"></i> <i class="fa fa-trash-o"></i></td>
                </tr>
            </tbody>
        </table>
        </div>

</div>


<?php Layout::includeLayout("footerBackend");

