<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
Layout::includeLayout('sidebar');
$roles = Data::get("roles");

?>
    <style>
        i {
            cursor: pointer;
        }
        .fa-eye {
            color: #39afff;
        }
        .fa-trash-o{
            color: #ff5853;
        }
    </style>
    <div class="content">
        <div class="container">
         <table  class="table table-hover" style="margin-top:20px ">
                <thead>
                <tr>
                    <th class="text-center" colspan="100%">Roles</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th colspan="100&" style="background-color: #a6ff73; color: white" class="text-center"><i class="fa fa-plus"></i> Create new</th>
                </tr>
                <?php
                foreach ($roles as $role){
                    ?>
                    <tr>
                        <td><?=$role->name?></td>
                        <td><i class="fa fa-trash-o"></i></td>
                    </tr>

                    <?php
                }
                ?>
                </tbody>
            </table>
        </div>

    </div>


<?php Layout::includeLayout("footerBackend");

