<?php

use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\Asset;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author"      content="Yaroslav Antonenko">

    <title>Shut the box</title>

    <?=AssetBundler::css()?>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png')?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css')?>" media="screen" >
    <link rel="stylesheet" href="<?= Asset::css('/game.css')?>" media="screen" >


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js')?>"></script>
    <script src="<?= Asset::js('respond.min.js')?>"></script>
    <![endif]-->
</head>
<style>
    body{
        background-image: url("<?=Asset::image('403.gif')?>");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: auto;
        background-position: center;
        background-color: #332851;
    }
</style>
<body class="home">
</body>
