-- MySQL Workbench Synchronization
-- Generated: 2020-05-06 23:03
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Yaroslav Antonenko

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `webproject`.`historygames` 
ADD COLUMN `Points` VARCHAR(45) NOT NULL AFTER `Date`;

ALTER TABLE `webproject`.`users` 
ADD COLUMN `BirthDate` DATETIME NOT NULL AFTER `Activeted`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
