<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
$error=Data::get("error");
$ban=Data::get("ban");

?>

	<!-- container -->
	<div class="container">
		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Sign in</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Entrar na sua conta</h3>
							<p class="text-center text-muted">Caso ainda não tenha conta podara  <a href="<?=Url::toRoute("user/register")?>">Registar-se</a> aqui, basta preencher os dados que lhe são pedidos. </p>
                            <hr>
                            <?php if($error!=0){?>
                            <div class="alert alert-danger alert-dismissible">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                <?php if($error==2){?>
                                <p><i class="fa fa-exclamation-circle fa-2x" style="color: red"></i> Você foi banido</p>
                                <?php }else{ ?>
                                <p><i class="fa fa-exclamation-circle fa-2x" style="color: red"></i> Verifique se inseriu os dados corretamente</p>
                                <?php } ?>
                            </div>
                            <?php } ?>
							<form action="<?=URL::toRoute("user/login")?>" method="post">
								<div class="top-margin">
									<label>Username <span class="text-danger">*</span></label>
									<input type="text" name="username" class="form-control">
								</div>
								<div class="top-margin">
									<label>Password <span class="text-danger">*</span></label>
									<input type="password" name="password" class="form-control">
								</div>

								<hr>

								<div class="row">
									<div class="col-md-12">
                                        <button class="btn btn-action" style="float: right" type="submit">Sign in</button>
                                    </div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>