<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
$user= Data::get("user");
$errors= Data::get("errors");
?>

    <div class="container">
        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Perfil</h1>
                </header>
                    <!-- Alert -->
                    <?php
                    if(is_array($errors)) {
                        if (isset($errors["password"])) {
                            ?>
                            <script>
                                $(".alert").alert();
                            </script>
                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                <p><?= $errors ?></p>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <?php
                        }
                    }
                    ?>
                    <div class="panel panel-default">
                        <div class="panel-body row">
                            <div class="col-md-3">
                                <img style="border: solid 1px black" class="img-circle" src="<?=Asset::image("User.png")?>">
                            </div>
                            <div class="col-md-6">
                                <header class="row">
                                    <h2 class="col-md-8"><?=$user->name?></h2>
                                    <button class="btn-warning btn col-md-4" data-toggle="modal" data-target="#EditUserModal"><i class="fa fa-pencil"></i> Editar</button>
                                </header>
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email:</label>
                                                <p><?=$user->email?></p>
                                            </div>
                                            <div class="col-md-6">
                                                <label>Data de Nascimeto:</label>
                                                <p><?=$user->birthdate->format("Y-m-d")?></p>
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Username:</label>
                                                <p><?=$user->username?></p>
                                            </div>
                                            <div class="col-md-6">
                                                <label>Password</label>
                                                <p>**************</p>
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Lugar:</label>
                                                <p>32</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>



                        </div>
                    </div>


            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>


<!-- Modal -->
<div class="modal fade" id="EditUserModal" tabindex="-1" role="dialog" aria-labelledby="EditUserModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Editar</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <h4>A preencher so os campos que quere alterar</h4>
                <form id="formEditUser" action="<?=URL::toRoute("user/edit",$user->iduser)?>" method="post">
                    <div class="top-margin">
                        <label>Nome Completo <span class="text-danger">*</span></label>
                        <input type="text" name="name" class="form-control" placeholder="<?=$user->name?>">
                    </div>
                    <div class="top-margin">
                        <label>Data Nascimento <span class="text-danger">*</span></label>
                        <input type="date" name="birthdate" class="form-control">
                    </div>
                    <div class="top-margin">
                        <label>Email <span class="text-danger">*</span></label>
                        <input type="text" name="email" class="form-control" placeholder="<?=$user->email?>">
                    </div>
                    <div class="top-margin">
                        <label>Password <span class="text-danger">*</span></label>
                        <input type="password" name="password" class="form-control">
                    </div>
                    <div class="top-margin">
                        <label>Confirma password <span class="text-danger">*</span></label>
                        <input type="password" name="confpassword" class="form-control">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="$('#formEditUser').submit()" class="btn btn-primary">Save changes</button>
            </div>

        </div>
    </div>
</div>
