<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>

    <div class="container">
        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Perfil</h1>
                </header>

                    <div class="panel panel-default">
                        <div class="panel-body row">
                            <div class="col-md-3">
                                <img style="border: solid 1px black" class="img-circle" src="<?=Asset::image("User.png")?>">
                            </div>
                            <div class="col-md-6">
                                <header class="row">
                                    <h2 class="col-md-8">Nome do Utilizador</h2>
                                    <button class="btn-warning btn col-md-4" data-toggle="modal" data-target="#EditUserModal"><i class="fa fa-pencil"></i> Editar</button>
                                </header>
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email:</label>
                                                <p>email@gmail.com</p>
                                            </div>
                                            <div class="col-md-6">
                                                <label>Data de Nascimeto:</label>
                                                <p>3/4/1999</p>
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Username:</label>
                                                <p>yar32</p>
                                            </div>
                                            <div class="col-md-6">
                                                <label>Password</label>
                                                <p>**************</p>
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Lugar:</label>
                                                <p>32</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th colspan="100%" class="text-center">Top 10</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1º</td>
                                            <td>Username</td>
                                        </tr>
                                        <tr>
                                            <td>2º</td>
                                            <td>Username</td>
                                        </tr>
                                        <tr>
                                            <td>3º</td>
                                            <td>Username</td>
                                        </tr>
                                        <tr>
                                            <td>4º</td>
                                            <td>Username</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>


            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>


<!-- Modal -->
<div class="modal fade" id="EditUserModal" tabindex="-1" role="dialog" aria-labelledby="EditUserModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Editar</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="top-margin">
                        <label>Nome Completo <span class="text-danger">*</span></label>
                        <input type="text" name="Name" class="form-control">
                    </div>
                    <div class="top-margin">
                        <label>Data Nascimento <span class="text-danger">*</span></label>
                        <input type="date" name="BirthDate" class="form-control">
                    </div>
                    <div class="top-margin">
                        <label>Email <span class="text-danger">*</span></label>
                        <input type="text" name="Email" class="form-control">
                    </div>
                    <div class="top-margin">
                        <label>Password <span class="text-danger">*</span></label>
                        <input type="password" name="Password" class="form-control">
                    </div>
                    <div class="top-margin">
                        <label>Confirma password <span class="text-danger">*</span></label>
                        <input type="password" name="ConfPassword" class="form-control">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
