<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;


Layout::includeLayout('header');
$user = Data::get('user');
$errors = Data::get('errors');
ErrMgr::attach($user);

?>

    <!-- container -->
    <div class="container">
        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Registar</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">Registar a sua conta</h3>
                            <p class="text-center text-muted">Se já tem conta é só fazer <a href="<?=Url::toRoute("user/login")?>">Login</a></p>
                            <hr>

                            <form action="<?=URL::toRoute("user/register")?>" method="post">
                                <div class="top-margin">
                                    <label>Nome Completo <span class="text-danger">*</span></label>
                                    <input type="text" name="name" class="form-control" value="<?=$user->name?>">
                                    <?= ErrMgr::bind('name') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Data Nascimento <span class="text-danger">*</span></label>
                                    <input type="date" name="birthdate" class="form-control" value="<?=(!empty($user->birthdate) ?$user->birthdate->format("Y-m-d"):"")?>">
                                    <?= ErrMgr::bind('birthdate') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Username <span class="text-danger">*</span></label>
                                    <input type="text" name="username" class="form-control" value="<?=$user->username?>">
                                    <?= ErrMgr::bind('username') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input type="email" name="email" class="form-control" value="<?=$user->email?>">
                                    <?= ErrMgr::bind('email') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Password <span class="text-danger">*</span></label>
                                    <input type="password" name="password" class="form-control">
                                    <?= ErrMgr::bind('password') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Confirma password <span class="text-danger">*</span></label>
                                    <input type="password" name="confpassword" class="form-control">
                                </div>

                                <hr>

                                <div class="row">
                                    <div class="col-lg-12 text-right">
                                        <button style="float: right" class="btn btn-action" type="submit">Sign up</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->
        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>