<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>

    <!-- container -->
    <div class="container">
        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Registar</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">Registar a sua conta</h3>
                            <p class="text-center text-muted">Se já tem conta é só fazer <a href="<?=Url::toRoute("user/login")?>">Login</a></p>
                            <hr>

                            <form>
                                <div class="top-margin">
                                    <label>Nome Completo <span class="text-danger">*</span></label>
                                    <input type="text" name="Name" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Data Nascimento <span class="text-danger">*</span></label>
                                    <input type="date" name="BirthDate" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Username <span class="text-danger">*</span></label>
                                    <input type="text" name="Username" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input type="text" name="Email" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Password <span class="text-danger">*</span></label>
                                    <input type="password" name="Password" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Confirma password <span class="text-danger">*</span></label>
                                    <input type="password" name="ConfPassword" class="form-control">
                                </div>

                                <hr>

                                <div class="row">
                                    <div class="col-lg-12 text-right">
                                        <button style="float: right" class="btn btn-action" type="submit">Sign up</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->
        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>